current: aft-production
default: aft-production
lagoons:
    aft-production:
        graphql: https://api.lagoon.sharemylesson.com/graphql
        hostname: ssh.lagoon.sharemylesson.com
        ui: https://ui.lagoon.sharemylesson.com/
        kibana: ""
        port: "2201"
        version: v2.19.0
        sshkey: ""
        sshportal: true
        publickeyidentities: []
updatecheckdisable: false
environmentfromdirectory: false
stricthostkeychecking: "no"
