#!/usr/bin/env bash

## Description: The sqlcmd utility lets you enter Transact-SQL statements, system procedures, and script files.
## Usage: sqlcmd [flags] [args]
## Example: "ddev sqlcmd" or "ddev sqlcmd -?" or "ddev sqlcmd -d DB_NAME"
## ExecRaw: true

/opt/mssql-tools18/bin/sqlcmd -S ${MSSQL_HOST} -P ${MSSQL_SA_PASSWORD} -U SA -d ${MSSQL_DB_NAME} -C "$@"
